# -*- coding: utf-8 -*-
"""Missing value analysis And Exploratory data analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ms7m3InG2Cv6tXsqRVZHfWrTHH38ONvd
"""

import numpy as np
import pandas as pd

data=pd.read_csv("cars.csv")

data.info()

data.describe()

data.shape

data.isnull().sum()

data.replace(" ",np.nan)

data.isnull().sum()*100/len(data)



d=pd.read_csv("customer_churn.csv")

d.head()

d.tail()

d.info()

d.shape

d1=d.isnull().sum()
d1

d.replace(' ',np.nan)

d2=d.isnull().sum()
d2

# loc  iloc

data.describe()

data.info()

# extract rows from 14 to 100 and columns from time-to-60-year
# use both loc n iloc
#

data.loc[14:100 , "time-to-60":"year"]

data.iloc[14:100+1,5:6+1]

df=pd.read_csv("customer_churn.csv")

df.info()

df.groupby('gender')

df.groupby('gender').sum()

df['gender'].value_counts()

